---
  cex.io: "https://cex.io/api/last_price/{0}/{1}"
# 0-Crypto currency
# 1-Real Money
# Cex. IO API
---
  coin.market.cap: "https://api.coinmarketcap.com/v1/ticker/"
# Coin Market Cap
---
  gdax.api: "https://api.gdax.com/products/{0}-USD/ticker"
